name: Build and Release APK

on:
  push:
    workflow_dispatch:


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout code
      uses: actions/checkout@v3

    # 设置 Java 环境
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    # 缓存 Gradle 构建目录
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # 确保 Gradle Wrapper 可执行
    - name: Make gradlew executable
      run: chmod +x ./gradlew

    # 构建 APK
    - name: Build APK
      run: ./gradlew assembleRelease

    # 调试输出构建结果
    - name: Debug APK build output
      run: ls -R app/build/outputs/apk

    # 上传构建结果作为 artifact
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

  release:
    name: Create GitHub Release and Upload APK
    runs-on: ubuntu-latest
    needs: build

    steps:
    # 检出代码（必要时）
    - name: Checkout code
      uses: actions/checkout@v3

    # 下载构建的 APK
    - name: Download APK Artifact
      uses: actions/download-artifact@v3
      with:
        name: release-apk
        path: ./release

    # 创建 Release
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    # 上传 APK 到 Release
    - name: Upload APK to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./release/app-release.apk
        asset_name: app-release.apk
        content_type: application/vnd.android.package-archive

