name: Build APK

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'  # 仅在版本标签推送时触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'  # 使用 Java 11

      - name: Install Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-7.2-all.zip -P $HOME/
          unzip $HOME/gradle-7.2-all.zip -d $HOME/
          export GRADLE_HOME=$HOME/gradle-7.2
          export PATH=$PATH:$GRADLE_HOME/bin

      - name: Build APK
        run: ./gradlew assembleDebug  # 构建调试版本的 APK

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: app/build/outputs/apk/debug/app-debug.apk  # APK 文件路径
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive

